# Generated by Django 4.1.2 on 2022-11-12 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iGroup', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerSheet',
            fields=[
                ('answer_sheet_id', models.AutoField(primary_key=True, serialize=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.student')),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('survey_id', models.AutoField(primary_key=True, serialize=False)),
                ('survey_name', models.CharField(max_length=20)),
                ('num_question', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=False)),
                ('send_survey', models.BooleanField(default=False)),
                ('instance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='iGroup.instance')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_type', models.CharField(choices=[('SINGLE', 'Single choice'), ('MULTIPLE', 'Multiple choice')], max_length=50)),
                ('question_index', models.IntegerField()),
                ('question_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('weight', models.IntegerField(default=0)),
                ('max_choice', models.IntegerField(default=1)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.survey')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_index', models.IntegerField()),
                ('choice_name', models.CharField(max_length=50)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.question')),
            ],
        ),
        migrations.CreateModel(
            name='ChoiceSingle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.answersheet')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.option')),
            ],
        ),
        migrations.CreateModel(
            name='ChoiceMultiple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('answer_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.answersheet')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.option')),
            ],
        ),
        migrations.AddField(
            model_name='answersheet',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.survey'),
        ),
    ]
