# Generated by Django 3.2 on 2022-11-09 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='max_choice',
        ),
    ]
