# Generated by Django 4.1.3 on 2022-12-09 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfigInstance",
            fields=[
                ("config_id", models.AutoField(primary_key=True, serialize=False)),
                ("max_num_pass", models.IntegerField()),
                ("num_group", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Instance",
            fields=[
                ("instance_id", models.AutoField(primary_key=True, serialize=False)),
                ("instance_name", models.CharField(max_length=256)),
                ("slug", models.SlugField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ResultQuestionScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_type", models.CharField(max_length=256)),
                ("question_weight", models.IntegerField()),
                ("question_score", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="ResultTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team_index", models.IntegerField()),
                ("team_name", models.CharField(max_length=256)),
                ("team_size", models.IntegerField(default=0)),
                ("total_score", models.FloatField()),
                (
                    "config_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="iGroup.configinstance",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "result_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="iGroup.resultteam",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.student",
                    ),
                ),
            ],
        ),
    ]
