# Generated by Django 4.1.3 on 2022-11-28 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("iGroup", "0001_initial"),
        ("survey", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="configinstance",
            name="survey",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="survey.survey"
            ),
        ),
    ]
